version: '3'
services:
  server:
    image: nestjs-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3003:3000' # porta da aplicação
      - '5555:5555' # porta do prisma studio
    depends_on:
    - database
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
      - /app/node_modules
    environment:
      - NODE_ENV=development
  database:
    image: mysql:8
    restart: always
    container_name: mysql_database_mercado
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: "mercadolivre"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: root
    volumes: # onde serão armazenadas as informações do banco
      - dbdata:/var/lib/mysql/

volumes:
  dbdata: